BASENAME_PLATFORM_VERSION := 1.0
BASENAME_BUILD_DATE := $(shell date -u +%Y%m%d-%H%M)

BASENAME_VERSION := BASENAME_$(BASENAME_PLATFORM_VERSION)-$(LINEAGE_BUILD)-$(BASENAME_BUILD_DATE)

# BASENAME version properties
PRODUCT_SYSTEM_PROPERTIES += \
    ro.basename.device=$(LINEAGE_BUILD) \
    ro.basename.version=$(BASENAME_VERSION)
